/* Live, browser-side UR10 view.  It renders the RViz URDF kinematic chain
 * from the read-only realtime joint stream and mounts the same four STL assets
 * used by the preliminary CAD RViz model.  It sends no ROS/UR command. */
import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { ColladaLoader } from "three/addons/loaders/ColladaLoader.js";
import { STLLoader } from "three/addons/loaders/STLLoader.js";

const host = document.getElementById("robot-3d");
const status = document.getElementById("robot-3d-status");

const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false });
renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
renderer.setClearColor(0x10151b);
renderer.outputColorSpace = THREE.SRGBColorSpace;
host.prepend(renderer.domElement);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(42, 1, 0.01, 8);
camera.position.set(1.05, -1.20, 0.95);
const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(-0.42, 0, 0.42);
controls.enableDamping = true;
controls.dampingFactor = 0.08;
controls.minDistance = 0.45;
controls.maxDistance = 4.2;
controls.update();

scene.add(new THREE.HemisphereLight(0xd9edff, 0x202830, 2.2));
const key = new THREE.DirectionalLight(0xffffff, 2.3);
key.position.set(1.2, -1.4, 2.5);
scene.add(key);
scene.add(new THREE.GridHelper(2.0, 20, 0x3e4b59, 0x26313d));
scene.add(new THREE.AxesHelper(0.18));

const arm = new THREE.Group();
scene.add(arm);
const baseLink = new THREE.Group();
const shoulder = new THREE.Group();
const upperArm = new THREE.Group();
const forearm = new THREE.Group();
const wrist1 = new THREE.Group();
const wrist2 = new THREE.Group();
const wrist3 = new THREE.Group();
const tool0 = new THREE.Group();
const linkGroups = { base_link: baseLink, shoulder_link: shoulder, upper_arm_link: upperArm,
  forearm_link: forearm, wrist_1_link: wrist1, wrist_2_link: wrist2,
  wrist_3_link: wrist3, tool0 };
Object.values(linkGroups).forEach(group => arm.add(group));

function translation(x, y, z) { return new THREE.Matrix4().makeTranslation(x, y, z); }
function rpy(roll, pitch, yaw) {
  return new THREE.Matrix4().makeRotationFromEuler(new THREE.Euler(roll, pitch, yaw, "XYZ"));
}
function pose(xyz, angles, q = 0) {
  return translation(...xyz).multiply(rpy(...angles)).multiply(new THREE.Matrix4().makeRotationZ(q));
}
function applyFixed(group, matrix) {
  group.matrixAutoUpdate = false;
  group.matrix.copy(matrix);
  group.matrixWorldNeedsUpdate = true;
}

// Browser never reimplements FK.  The bridge evaluates the same complete URDF
// used by RViz and sends absolute link matrices from that authoritative chain.
function updateArm(matrices) {
  if (!matrices) return;
  Object.entries(linkGroups).forEach(([name, group]) => {
    const values = matrices[name];
    if (!Array.isArray(values) || values.length !== 16) return;
    const matrix = new THREE.Matrix4().set(...values);
    applyFixed(group, matrix);
  });
}

// The CAD assembly is exported in millimetres.  These are the exact mounting
// transform and origin generated by build_urdf_with_cad_meshes.py (tool_yaw=270).
const cadAssembly = new THREE.Group();
cadAssembly.matrixAutoUpdate = false;
const cadToTool = new THREE.Matrix4().set(
  1, 0, 0, 0,
  0, 0, 1, 0,
  0, -1, 0, 0,
  0, 0, 0, 1,
);
const cadMount = new THREE.Matrix4().makeRotationZ(THREE.MathUtils.degToRad(270)).multiply(cadToTool);
const cadOrigin = new THREE.Vector3(327.612, 238.738, 80.221).applyMatrix4(cadMount).multiplyScalar(-0.001);
cadMount.setPosition(cadOrigin);
cadAssembly.matrix.copy(cadMount);
tool0.add(cadAssembly);

const stlAssets = [
  ["末端执行器 - 2F85-CLOSED_20181108.step-1.STL", 0x27313a],
  ["末端执行器 - 3D相机-1.STL", 0xd46a42],
  ["末端执行器 - 六轴力-1.STL", 0x205eb8],
  ["末端执行器 - 连接1-1.STL", 0xa2abb4],
];
const loader = new STLLoader();
// These are the actual DAE visual meshes from the URDF used by RViz.  The STL
// collision meshes remain in model/ur10/ for collision work, but are not used
// for the dashboard picture.
const ur10Assets = [
  ["base.dae", baseLink, [0, 0, 0], [0, 0, Math.PI]],
  ["shoulder.dae", shoulder, [0, 0, 0], [0, 0, Math.PI]],
  ["upperarm.dae", upperArm, [0, 0, 0.220941], [Math.PI / 2, 0, -Math.PI / 2]],
  ["forearm.dae", forearm, [0, 0, 0.049042], [Math.PI / 2, 0, -Math.PI / 2]],
  ["wrist1.dae", wrist1, [0, 0, -0.1149], [Math.PI / 2, 0, 0]],
  ["wrist2.dae", wrist2, [0, 0, -0.1158], [0, 0, 0]],
  ["wrist3.dae", wrist3, [0, 0, -0.0922], [Math.PI / 2, 0, 0]],
];
function loadStl(url, parent, color, localMatrix = null, scale = 0.001) {
  return new Promise((resolve, reject) => loader.load(url, geometry => {
    geometry.computeVertexNormals();
    const mesh = new THREE.Mesh(geometry, new THREE.MeshStandardMaterial({ color, roughness: 0.42, metalness: 0.55 }));
    mesh.scale.setScalar(scale);
    if (localMatrix) {
      mesh.matrixAutoUpdate = false;
      mesh.matrix.copy(localMatrix);
    }
    parent.add(mesh);
    resolve();
  }, undefined, reject));
}
const cadLoads = stlAssets.map(([name, color]) => {
  const url = "/model/solidworks/end_effector/" + encodeURIComponent(name);
  return loadStl(url, cadAssembly, color);
});
const daeLoader = new ColladaLoader();
function loadDae(url, parent, localMatrix) {
  return new Promise((resolve, reject) => daeLoader.load(url, asset => {
    const mesh = asset.scene;
    mesh.matrixAutoUpdate = false;
    mesh.matrix.copy(localMatrix);
    parent.add(mesh);
    resolve();
  }, undefined, reject));
}
const armLoads = ur10Assets.map(([name, parent, xyz, angles]) => {
  return loadDae("/model/ur10/visual/" + name, parent, pose(xyz, angles));
});
Promise.all([...cadLoads, ...armLoads]).then(() => {
  status.textContent = "完整 UR10 + SolidWorks STL 已加载 · 关节状态实时同步";
  // Frame the full robot only once after all mesh bounds are known.  Subsequent
  // joint updates preserve the operator's chosen view instead of snapping it.
  requestAnimationFrame(() => {
    arm.updateMatrixWorld(true);
    const box = new THREE.Box3().setFromObject(arm);
    const center = box.getCenter(new THREE.Vector3());
    const size = box.getSize(new THREE.Vector3());
    const radius = Math.max(size.x, size.y, size.z) * 0.62;
    const distance = radius / Math.tan(THREE.MathUtils.degToRad(camera.fov * 0.5));
    camera.position.copy(center).add(new THREE.Vector3(0.95, -1.15, 0.78).normalize().multiplyScalar(distance));
    controls.target.copy(center);
    controls.update();
  });
}).catch(error => {
  console.error("SolidWorks STL load failed", error);
  status.textContent = "STL 加载失败（模型文件不可用）";
});

function resize() {
  const width = Math.max(280, host.clientWidth), height = Math.max(210, host.clientHeight);
  renderer.setSize(width, height, false);
  camera.aspect = width / height;
  camera.updateProjectionMatrix();
}
new ResizeObserver(resize).observe(host);
resize();
window.addEventListener("ur10-realtime-state", event => updateArm(event.detail.link_world_matrices));
if (window.latestRobotState) updateArm(window.latestRobotState.link_world_matrices);

function render() {
  controls.update();
  renderer.render(scene, camera);
  requestAnimationFrame(render);
}
render();
