/* Live, browser-side UR10 view.  It renders the nominal UR10 kinematic chain
 * from the read-only realtime joint stream and mounts the same four STL assets
 * used by the preliminary CAD RViz model.  It sends no ROS/UR command. */
import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { STLLoader } from "three/addons/loaders/STLLoader.js";

const host = document.getElementById("robot-3d");
const status = document.getElementById("robot-3d-status");

const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false });
renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
renderer.setClearColor(0x10151b);
renderer.outputColorSpace = THREE.SRGBColorSpace;
host.prepend(renderer.domElement);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(42, 1, 0.01, 8);
camera.position.set(1.45, -1.65, 1.15);
const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(-0.35, 0, 0.45);
controls.enableDamping = true;
controls.dampingFactor = 0.08;
controls.minDistance = 0.45;
controls.maxDistance = 4.2;
controls.update();

scene.add(new THREE.HemisphereLight(0xd9edff, 0x202830, 2.2));
const key = new THREE.DirectionalLight(0xffffff, 2.3);
key.position.set(1.2, -1.4, 2.5);
scene.add(key);
scene.add(new THREE.GridHelper(2.4, 24, 0x3e4b59, 0x26313d));
scene.add(new THREE.AxesHelper(0.18));

const arm = new THREE.Group();
scene.add(arm);
const tool0 = new THREE.Group();
arm.add(tool0);
const metal = new THREE.MeshStandardMaterial({ color: 0x53677a, roughness: 0.43, metalness: 0.62 });
const jointMat = new THREE.MeshStandardMaterial({ color: 0x2b3845, roughness: 0.36, metalness: 0.72 });
const linkMeshes = [];
const jointMeshes = [];

function sphere(radius) {
  const mesh = new THREE.Mesh(new THREE.SphereGeometry(radius, 20, 14), jointMat);
  arm.add(mesh); jointMeshes.push(mesh); return mesh;
}
function bar() {
  const mesh = new THREE.Mesh(new THREE.CylinderGeometry(0.042, 0.055, 1, 18), metal);
  arm.add(mesh); linkMeshes.push(mesh); return mesh;
}
for (let i = 0; i < 7; i++) sphere(i === 0 ? 0.085 : 0.064);
for (let i = 0; i < 6; i++) bar();
const base = new THREE.Mesh(new THREE.CylinderGeometry(0.115, 0.14, 0.125, 32), jointMat);
base.position.z = 0.0625;
arm.add(base);

function translation(x, y, z) { return new THREE.Matrix4().makeTranslation(x, y, z); }
function rpy(roll, pitch, yaw) {
  return new THREE.Matrix4().makeRotationFromEuler(new THREE.Euler(roll, pitch, yaw, "XYZ"));
}
function joint(parent, xyz, angles, q) {
  return parent.clone().multiply(translation(...xyz)).multiply(rpy(...angles))
    .multiply(new THREE.Matrix4().makeRotationZ(q));
}
function setBar(mesh, a, b) {
  const delta = b.clone().sub(a), length = delta.length();
  mesh.position.copy(a).add(b).multiplyScalar(0.5);
  mesh.scale.set(1, length, 1);
  mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), delta.normalize());
}

// Same kinematic origins as the UR10 CB3 URDF used by RViz.  This is nominal
// geometry only; the realtime values are q_actual read from 30013/30003.
function updateArm(q) {
  if (!Array.isArray(q) || q.length !== 6 || q.some(v => !Number.isFinite(v))) return;
  let m = new THREE.Matrix4().makeRotationZ(Math.PI); // base_link -> base_link_inertia
  const frames = [new THREE.Vector3(0, 0, 0)];
  m = joint(m, [0, 0, 0.1273], [0, 0, 0], q[0]); frames.push(new THREE.Vector3().setFromMatrixPosition(m));
  m = joint(m, [0, 0, 0], [Math.PI / 2, 0, 0], q[1]); frames.push(new THREE.Vector3().setFromMatrixPosition(m));
  m = joint(m, [-0.612, 0, 0], [0, 0, 0], q[2]); frames.push(new THREE.Vector3().setFromMatrixPosition(m));
  m = joint(m, [-0.5723, 0, 0.163941], [0, 0, 0], q[3]); frames.push(new THREE.Vector3().setFromMatrixPosition(m));
  m = joint(m, [0, -0.1157, 0], [Math.PI / 2, 0, 0], q[4]); frames.push(new THREE.Vector3().setFromMatrixPosition(m));
  m = joint(m, [0, 0, 0.0922], [Math.PI / 2, Math.PI, Math.PI], q[5]); frames.push(new THREE.Vector3().setFromMatrixPosition(m));
  jointMeshes.forEach((mesh, i) => mesh.position.copy(frames[Math.min(i, frames.length - 1)]));
  linkMeshes.forEach((mesh, i) => setBar(mesh, frames[i], frames[i + 1]));
  // URDF: wrist_3 -> flange -> tool0 fixed transforms.
  m.multiply(rpy(0, -Math.PI / 2, -Math.PI / 2)).multiply(rpy(Math.PI / 2, 0, Math.PI / 2));
  tool0.matrixAutoUpdate = false;
  tool0.matrix.copy(m);
  tool0.matrixWorldNeedsUpdate = true;
}

// The CAD assembly is exported in millimetres.  These are the exact mounting
// transform and origin generated by build_urdf_with_cad_meshes.py (tool_yaw=270).
const cadAssembly = new THREE.Group();
cadAssembly.matrixAutoUpdate = false;
const cadToTool = new THREE.Matrix4().set(
  1, 0, 0, 0,
  0, 0, 1, 0,
  0, -1, 0, 0,
  0, 0, 0, 1,
);
const cadMount = new THREE.Matrix4().makeRotationZ(THREE.MathUtils.degToRad(270)).multiply(cadToTool);
const cadOrigin = new THREE.Vector3(327.612, 238.738, 80.221).applyMatrix4(cadMount).multiplyScalar(-0.001);
cadMount.setPosition(cadOrigin);
cadAssembly.matrix.copy(cadMount);
tool0.add(cadAssembly);

const stlAssets = [
  ["末端执行器 - 2F85-CLOSED_20181108.step-1.STL", 0x27313a],
  ["末端执行器 - 3D相机-1.STL", 0xd46a42],
  ["末端执行器 - 六轴力-1.STL", 0x205eb8],
  ["末端执行器 - 连接1-1.STL", 0xa2abb4],
];
const loader = new STLLoader();
Promise.all(stlAssets.map(([name, color]) => new Promise((resolve, reject) => {
  const url = "/model/solidworks/end_effector/" + encodeURIComponent(name);
  loader.load(url, geometry => {
    geometry.computeVertexNormals();
    const mesh = new THREE.Mesh(geometry, new THREE.MeshStandardMaterial({ color, roughness: 0.42, metalness: 0.55 }));
    mesh.scale.setScalar(0.001); // SolidWorks STL is in mm
    cadAssembly.add(mesh);
    resolve();
  }, undefined, reject);
}))).then(() => {
  status.textContent = "STL 已加载 · 关节状态实时同步";
}).catch(error => {
  console.error("SolidWorks STL load failed", error);
  status.textContent = "STL 加载失败（模型文件不可用）";
});

function resize() {
  const width = Math.max(280, host.clientWidth), height = Math.max(210, host.clientHeight);
  renderer.setSize(width, height, false);
  camera.aspect = width / height;
  camera.updateProjectionMatrix();
}
new ResizeObserver(resize).observe(host);
resize();
window.addEventListener("ur10-realtime-state", event => updateArm(event.detail.q));
if (window.latestRobotState) updateArm(window.latestRobotState.q);

function render() {
  controls.update();
  renderer.render(scene, camera);
  requestAnimationFrame(render);
}
render();
